---
- name: Execute PowerShell script on Windows host
  hosts: windows
  gather_facts: false  # Correctly set to a boolean value with proper indentation
  tasks:
    - name: Run a PowerShell script from a specific location
      ansible.windows.win_shell: |
        C:\Scripts\ExampleScript.ps1
      args:
        executable: powershell.exe
