---
- name: Execute PowerShell script on Windows host
  hosts: windows
  gather_facts: false
  tasks:
    - name: Run a PowerShell script from a specific location
      ansible.windows.win_shell: |
        C:\Scripts\ExampleScriptAnsible.ps1
      args:
        executable: powershell.exe
      register: script_output

    - name: Print the output for debugging purposes
      debug:
        var: script_output.stdout

    - name: Create a file if condition is met
      ansible.builtin.file:
        path: /tmp/trigger_file.txt
        state: touch
      when: '"specific_output_condition" in script_output.stdout'
