---
- name: Execute PowerShell script on Windows host
  hosts: windows
  gather_facts: false  # Correctly set to a boolean value with proper indentation
  tasks:
    - name: Run a PowerShell script
      ansible.windows.win_shell: |
        Write-Output "Hello, this is a test from PowerShell"
      args:
        executable: powershell.exe
