---
- name: Execute PowerShell script on Windows host
  hosts: windows
  gather_facts: false
  tasks:
    - name: Run a PowerShell script from a specific location
      ansible.windows.win_shell: |
        C:\Scripts\ExampleScriptAnsible.ps1
      args:
        executable: powershell.exe
      register: script_output

    - name: Print the output for debugging purposes
      debug:
        var: script_output.stdout

    - name: Create a trigger file if condition is met
      ansible.windows.win_shell: |
        New-Item -Path C:\Scripts\trigger_file.txt -ItemType File
      when: '"specific_output_condition" in script_output.stdout'
