---
- name: Run PowerShell Script on Windows Server
  hosts: windows
  gather_facts: no
  vars:
    script_source: "C:\Users\beheerder\Desktop\Scripts" 
    script_destination: "C:\Users\beheerder\Desktop\Scripts"

  tasks:
    - name: Ensure temp directory exists
      win_file:
        path: C:\temp
        state: directory

    - name: Copy PowerShell script to Windows Server
      win_copy:
        src: "{{ script_source }}"
        dest: "{{ script_destination }}"

    - name: Run PowerShell script
      win_shell: |
        PowerShell.exe -ExecutionPolicy Bypass -File "{{ script_destination }}"
      register: script_output

    - name: Show script output
      debug:
        var: script_output.stdout
