---
- name: Run PowerShell Script on Windows Server
  hosts: windows
  gather_facts: no
  vars:
    script_path: "C:\\Users\\beheerder\\Desktop\\Scripts\\Do-Service-Restart.ps1"  
  tasks:
    - name: Run PowerShell script
      win_shell: |
        PowerShell.exe -ExecutionPolicy Bypass -File "{{ script_path }}"
      register: script_output

    - name: Show script output
      debug:
        var: script_output.stdout
