---
- name: Execute trigger PowerShell script on Windows host
  hosts: windows
  gather_facts: false
  tasks:
    - name: Run the trigger PowerShell script
      ansible.windows.win_shell: |
        C:\Scripts\TriggerScript.ps1
      args:
        executable: powershell.exe
