- name: Create Azure VM with Variables and Run a Script
  hosts: localhost
  tasks:
    - name: Create virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: '{{ resource_group }}'
        name: '{{ virtual_network_name }}'
        address_prefixes: '{{ address_prefixes }}'

    - name: Add subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: '{{ resource_group }}'
        name: '{{ subnet_name }}'
        address_prefix: '{{ subnet_address_prefix }}'
        virtual_network: '{{ virtual_network_name }}'

    - name: Create public IP address
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: '{{ resource_group }}'
        allocation_method: Static
        name: '{{ public_ip_name }}'
      register: output_ip_address

    - name: Output public IP
      debug:
        msg: 'The public IP is {{ output_ip_address.state.ip_address }}'

    - name: Create Network Security Group
      azure.azcollection.azure_rm_securitygroup:
        resource_group: '{{ resource_group }}'
        name: '{{ security_group_name }}'
        rules:
          - name: allow_rdp
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: allow_web_traffic
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
          - name: allow_winrm_https
            protocol: Tcp
            destination_port_range: 5986
            access: Allow
            priority: 1003
            direction: Inbound

    - name: Create a network interface
      azure.azcollection.azure_rm_networkinterface:
        name: nic
        resource_group: '{{ resource_group }}'
        virtual_network: '{{ virtual_network_name }}'
        subnet_name: '{{ subnet_name }}'
        security_group: '{{ security_group_name }}'
        ip_configurations:
          - name: default
            public_ip_address_name: '{{ public_ip_name }}'
            primary: true

    - name: Create VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: '{{ resource_group }}'
        name: '{{ vm_name }}'
        vm_size: '{{ vm_size }}'
        admin_username: '{{ admin_username }}'
        admin_password: '{{ admin_password }}'
        network_interfaces: nic
        os_type: Windows
        image:
          offer: '{{ image_offer }}'
          publisher: '{{ image_publisher }}'
          sku: '{{ image_sku }}'
          version: '{{ image_version }}'
      no_log: false

    - name: Install and configure WinRM on the new VM
      azure.azcollection.azure_rm_virtualmachineextension:
        resource_group: '{{ resource_group }}'
        virtual_machine_name: '{{ vm_name }}'
        name: configureWinRM
        publisher: Microsoft.Compute
        virtual_machine_extension_type: CustomScriptExtension
        type_handler_version: '1.10'
        settings:
          commandToExecute: |
            powershell -ExecutionPolicy Unrestricted -Command "
              try {
                  # Installeer en start WinRM indien nodig
                  if ((Get-Service -Name WinRM -ErrorAction SilentlyContinue) -eq $null) {
                      Install-WindowsFeature -Name WinRM
                      Set-Service -Name WinRM -StartupType Automatic
                      Start-Service -Name WinRM
                  } else {
                      Start-Service -Name WinRM
                  }

                  # Configureer WinRM-luisteraar en instellingen
                  Write-Output 'Configuring WinRM...'
                  winrm quickconfig -force | Out-String;
                  winrm set winrm/config/service/auth '@{Basic=\"true\"}' | Out-String;
                  winrm set winrm/config/service '@{AllowUnencrypted=\"true\"}' | Out-String;

                  # Maak HTTPS-luisteraar aan als deze nog niet bestaat
                  if (-not (Get-Item -Path WSMan:\\localhost\\Listener | Where-Object { $_.Keys -eq 'Transport=HTTPS' })) {
                      $cert = New-SelfSignedCertificate -DnsName '{{ vm_name }}' -CertStoreLocation Cert:\\LocalMachine\\My;
                      New-Item -Path WSMan:\\localhost\\Listener -Transport HTTPS -Address * -CertificateThumbprint $cert.Thumbprint | Out-String;
                  }

                  # Voeg firewallregel toe voor WinRM HTTPS
                  New-NetFirewallRule -DisplayName 'Allow WinRM HTTPS' -Direction Inbound -Protocol TCP -LocalPort 5986 -Action Allow | Out-String;
              }
              catch {
                  Write-Output 'An error occurred during script execution.'
                  Write-Output $_.Exception.Message
              }
            "
      register: winrm_extension
      retries: 3
      delay: 15

    - name: Show output of WinRM configuration
      debug:
        msg: '{{ winrm_extension }}'

    - name: Wait for 30 seconds before connecting to the new VM
      wait_for:
        timeout: 30

    - name: Add the new VM to the inventory
      add_host:
        name: newhost
        ansible_host: '{{ output_ip_address.state.ip_address }}'
        ansible_user: '{{ admin_username }}'
        ansible_password: '{{ admin_password }}'
        ansible_port: 5986
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore

- name: Configure the new VM
  hosts: newhost
  tasks:
    - name: Test reachability of the Windows VM (Ping check)
      ansible.windows.win_ping:

    - name: Create Notepad file with text "het werkt" on the Desktop
      ansible.windows.win_shell: |
        $desktopPath = "C:\Users\{{ ansible_user }}\Desktop"
        New-Item -Path $desktopPath -Name 'test.txt' -ItemType 'file' -Force
        Add-Content -Path "$desktopPath\test.txt" -Value "het werkt"
