---
- name: Deploy Azure Windows VM with additional features
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    azure_credentials:
      client_id: "<your-client-id>"
      secret: "<your-client-secret>"
      tenant: "<your-tenant-id>"
      subscription_id: "<your-subscription-id>"
    vm_parameters:
      resource_group: "automation-rg"
      vm_name: "winTest-vm"
      vm_size: "Standard_DS1_v2"
      admin_username: "beheerder"
      admin_password: "{{ admin_password }}"
      network_interface_name: "hix365-hub-vnet"
      os_type: "Windows"
      availability_set: "winTest-avail-set"  # Toevoegen van een availability set
      managed_disk_type: "Standard_LRS"      # Gebruik van managed disk
      image:
        offer: "WindowsServer"
        publisher: "MicrosoftWindowsServer"
        sku: "2019-Datacenter"
        version: "latest"
  vars_prompt:
    - name: "admin_password"
      prompt: "Enter the admin password for the VM"
      private: yes
  tasks:

    - name: Create resource group if not exists
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ vm_parameters.resource_group }}"
        location: "westeurope"

    - name: Create an availability set
      azure.azcollection.azure_rm_availabilityset:
        name: "{{ vm_parameters.availability_set }}"
        resource_group: "{{ vm_parameters.resource_group }}"
        platform_update_domain_count: 5
        platform_fault_domain_count: 2
        sku: Aligned

    - name: Authenticate and create VM with managed disk and availability set
      azure.azcollection.azure_rm_virtualmachine:
        client_id: "{{ azure_credentials.client_id }}"
        secret: "{{ azure_credentials.secret }}"
        tenant: "{{ azure_credentials.tenant }}"
        subscription_id: "{{ azure_credentials.subscription_id }}"
        state: present
        resource_group: "{{ vm_parameters.resource_group }}"
        name: "{{ vm_parameters.vm_name }}"
        vm_size: "{{ vm_parameters.vm_size }}"
        admin_username: "{{ vm_parameters.admin_username }}"
        admin_password: "{{ admin_password }}"
        availability_set: "{{ vm_parameters.availability_set }}"  # Voeg availability set toe
        managed_disk_type: "{{ vm_parameters.managed_disk_type }}"  # Gebruik managed disk
        network_interfaces:
          - name: "{{ vm_parameters.network_interface_name }}"
        os_type: "{{ vm_parameters.os_type }}"
        image:
          offer: "{{ vm_parameters.image.offer }}"
          publisher: "{{ vm_parameters.image.publisher }}"
          sku: "{{ vm_parameters.image.sku }}"
          version: "{{ vm_parameters.image.version }}"
      register: vm_result
      no_log: true

    - name: Enable boot diagnostics
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ vm_parameters.resource_group }}"
        name: "{{ vm_parameters.vm_name }}"
        boot_diagnostics:
          enabled: true
          storage_uri: "https://<your_storage_account>.blob.core.windows.net/"
      register: boot_diagnostics_result

    - name: Start VM after deployment
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ vm_parameters.resource_group }}"
        name: "{{ vm_parameters.vm_name }}"
        started: true

    - name: Show VM deployment result
      debug:
        var: vm_result
