- name: Configure the new VM
  hosts: newhost
  tasks:
    - name: Test reachability of the Windows VM (Ping check)
      ansible.windows.win_ping:

    - name: Create Notepad file with text "het werkt" on the Desktop
      ansible.windows.win_shell: |
        $desktopPath = "C:\Users\{{ ansible_user }}\Desktop"
        New-Item -Path $desktopPath -Name 'test.txt' -ItemType 'file' -Force
        Add-Content -Path "$desktopPath\test.txt" -Value "het werkt"
