---
- name: Configure FortiGate with PowerFGT
  hosts: fortigate_server
  tasks:
    - name: Run PowerShell script to configure FortiGate
      ansible.windows.win_shell: |
        PowerShell.exe -ExecutionPolicy Bypass -File "C:\Scripts\FirewallConfiguratie.ps1" -Server "{{ server }}" -Username "{{ username }}" -Password "{{ password }}" -GroupName "{{ group_name }}" -Member1 "{{ member1 }}" -Member2 "{{ member2 }}" -Interface "{{ interface }}" -IPAddress "{{ ip_address }}" -Netmask "{{ netmask }}" -Comment "{{ comment }}"
